### ISSUE TITLE
Merchant Page 2.0, TOKENIZATION not working 

### ISSUE THREAD

**Issue by ermuhaimin** [payfort/payfort-php-sdk#11]
I attempted to integrate TOKENIZATION with card details, but I am getting response_code as 00027 and response_message as "Invalid extra parameters".

But if I remove card details from the request then it will redirect to the PayFort Payment page (https://sbcheckout.payfort.com/FortAPI/paymentPage) and able to complete the transaction.

**Request Parameters**

  service_command = TOKENIZATION
  merchant_identifier = W******M
  access_code = xMs0V******v4Of4em
  merchant_reference = 58ac0b23a888a
  language  en
  return_url = http://localhost/payfort-php-sdk-master/route.php?r=merchantPageReturn
  token_name = Mn******Van
  signature = 9afd783ed82a69c6b128fd6b34bced6c05975e68a086a0529eaebbec79a93dfa
  card_number = 455701******8902
  expiry_date = 1705
  card_security_code = 123

**Response Parameters**

**response_code**	 00027
service_command	TOKENIZATION
card_number	455701******8902
**response_message**	**Invalid extra parameters**
merchant_identifier	W******M
merchant_reference	8813128471
expiry_date	1705
access_code	xMs0V******v4Of4em
return_url	     http://localhost/payfort-php-sdk-master/route.php?r=merchantPageReturn
language	en
status	00
error_msg	**Invalid extra parameters**

**Comment by mohannadsaleh** [comment]
Hello,

Can you please contact integration@payfort.com they will be best point of contact to help you with the required integration settings and steps to integrate your site with PAYFORT .

Best Regards,
