### ISSUE TITLE
Merchant Page 2.0 "Invalid extra parameters"

### ISSUE THREAD

**Issue by ahmedsaoud31** [payfort/payfort-php-sdk#13]
when i use Merchant Page 2.0 i receive "Invalid extra parameters" error.

**Comment by mohannadsaleh** [comment]
Thank you for leaving your feedback,

I have replied to your email , adding integration@payfot.com for further integration assistance needed . 

Mohannad Saleh

**Comment by bilalejaz505** [comment]
I am also facing the same issue. Need to integrate it in laravel project. I have installed it through composer and running its example code giving this error. Please help me :(

**Comment by mohannadsaleh** [comment]
Hello,

Thank you for contacting us , can you please share more details about this error you are facing .

Best Regards, 
Mohannad Saleh

**Comment by codekipple** [comment]
I am also experiencing this problem.
Here's an example of the form I'm submitting for a test transaction with some info redacted:-

    <form id="payfort_payment" action="https://sbcheckout.payfort.com/FortAPI/paymentPage" method="POST">
        <input type="hidden" id="merchant_identifier" name="merchant_identifier" value="redacted">
        <input type="hidden" id="access_code" name="access_code" value="redacted">
        <input type="hidden" id="merchant_reference" name="merchant_reference" value="redacted">
        <input type="hidden" id="language" name="language" value="en">
        <input type="hidden" id="service_command" name="service_command" value="TOKENIZATION">
        <input type="hidden" id="return_url" name="return_url" value="redacted">
        <input type="hidden" id="signature" name="signature" value="redacted">
        <input type="hidden" id="card_number" name="card_number" value="4005550000000001">
        <input type="hidden" id="card_holder_name" name="card_holder_name" value="Mr Smith">
        <input type="hidden" id="card_security_code" name="card_security_code" value="123">
        <input type="hidden" id="expiry_date" name="expiry_date" value="2105">
    </form>

When I submit it I get this response:-

    array (size=12)
        'response_code' => string '00027'
        'service_command' => string 'TOKENIZATION'
        'card_number' => string '400555******0001'
        'response_message' => string 'Invalid extra parameters'
        'signature' => string 'redacted'
        'merchant_identifier' => string 'redacted'
        'merchant_reference' => string 'redacted'
        'expiry_date' => string '2105'
        'access_code' => string 'redacted'
        'return_url' => string 'redacted'
        'language' => string 'en'
        'status' => string '00'

Could this error be triggered by an invalid signature? I think I'm creating the signature correctly. I'm not sending any extra parameters.

**Comment by codekipple** [comment]
Sorry realised my account is set to use Merchant Page not Merchant Page 2.0. So I was sending Merchange Page parameters 2.0 when I shouldn't be. All works now.

**Comment by sanjaykumar2338** [comment]
**Sorry realised my account is set to use Merchant Page not Merchant Page 2.0. So I was sending Merchange Page parameters 2.0 when I shouldn't be. All works now.**

I am also facing the same problem.  So i want to know where you passing the Merchange Page parameters 2.0 ?

**Comment by codekipple** [comment]
@sanjaykumar2338 I was passing parameters intended for Merchant page 2.0. After checking my payfort admin I realised I was not actually using Merchant page 2.0. I was simply using Merchant page which expects different parameters.

**Comment by sanjaykumar2338** [comment]
Intended parameter

Pls  give example

**Comment by mohannadsaleh** [comment]
Hello , 

For more details on your integration and parameters required for your account , your best point of contact is our integration team integration@payfort.com , they will assist you with the need details and certificate your integration .

Best Regards, 
Mohannad Saleh

**Comment by codekipple** [comment]
@sanjaykumar2338 if your using Merchant page this page details the parameters
https://docs.payfort.com/docs/merchant-page/build/index.html#merchant-page-request

**Comment by sanjaykumar2338** [comment]
No, I am using merchant 2.0 and in my payfort account only merchant page method added.

So merchant page work for merchant page 2.0 ?

**Comment by codekipple** [comment]
@sanjaykumar2338 

These parameters are for merchant page:-
https://docs.payfort.com/docs/merchant-page/build/index.html

The parameters are for merchant page 2.0:-
https://docs.payfort.com/docs/merchant-page-two/build/index.html

You have to use the correct one based on what method is enabled in your payfort account.

**Comment by sanjaykumar2338** [comment]
Ok i am doing with merchant page 2.0 , but receiving the following response :


  | Array
-- | --
  | (
  | [response_code] => 00027
  | [card_number] => 400555******0001
  | [response_message] => Invalid extra parameters
  | [service_command] => TOKENIZATION
  | [signature] => 895c5e5b98cf388aab8a619f167a22962668a277b8fa3a4afd79d34e69aefd63
  | [merchant_identifier] => 
  | [merchant_reference] => 123456
  | [access_code] => 
  | [expiry_date] => 2105
  | [return_url] => http://www.mytourisma.com/ticket/testapi
  | [language] => en
  | [status] => 00
  | )
 
I have removed a access code and merchant identifier value.

https://prnt.sc/h7qoon in my account only merchant page is active.

**Comment by sanjaykumar2338** [comment]
This is request :

<?php
	 $arrData = array(
				'merchant_identifier' => 'cjXYnVPO',
				'access_code'         => '',
				'merchant_reference'  => '123456',
				'service_command'     => 'TOKENIZATION',
				'language'            => 'en',
				'return_url'          => 'http://www.mytourisma.com/ticket/testapi',
			);
			
	 $shaString             = '';
        ksort($arrData);
        foreach ($arrData as $k => $v) {
            $shaString .= "$k=$v";
        }

      
            $shaString = 'TESTSHAIN'.$shaString.'TESTSHAIN';
      
			$signature = hash('sha256', $shaString);
     
?>
<!DOCTYPE html>
<html>
<head>
	<title>Payment Form</title>
</head>
<body>
<form method="post" action="https://sbcheckout.PayFort.com/FortAPI/paymentPage">
merchant_identifier: <input type="text" name="merchant_identifier" value="cjXYnVPO"><br>
access_code: <input type="text" name="access_code" value=""><br>	
merchant_reference: <input type="text" name="merchant_reference" value="123456"><br>
service_command: <input type="text" name="service_command" value="TOKENIZATION"><br>
language: <input type="text" name="language" value="en"><br>
return_url: <input type="text" name="return_url" value="http://www.mytourisma.com/ticket/testapi"><br>
expiry_date: <input type="text" name="expiry_date" value="2105"><br>
card_number: <input type="text" name="card_number" value="4005550000000001"><br>
card_security_code: <input type="text" name="card_security_code" value="123"><br>
signature: <input type="text" name="signature" value="<?php echo $signature; ?>"><br>
<input type="submit" value="Submit">
</form>
</body>
</html>


I have removed a access code value.

**Comment by ahmedsaoud31** [comment]
@sanjaykumar2338 
Use
https://github.com/ahmedsaoud31/payfort-php

**Comment by mohannadsaleh** [comment]
Hi @sanjaykumar2338

Integration team should activate and verify merchant page integration requests in order to be processed successfully, 

Please always use the SDKs offered by payfort team to integrate with PAYFORT , we also offer the support and certification for integration with payfort , please contact integration team using below email 

integration@payfort.com

They will always reply very fast and keep the follow up process with you in order to finish the certification of your integration smoothly.

Please let me know if you need more assistance .
All the best 
Mohannad Saleh

**Comment by sanjaykumar2338** [comment]
Thanks , the issue has been resolved. There is an issue with account .

**Comment by mbilal117** [comment]
Hi I am facing a problem while submitting form payfort return response in html format.One more thing what should be the return_url?
 any help?

**Comment by sanjaykumar2338** [comment]
**return_url** where payfort return response.

Follow this link https://github.com/payfort/payfort-php-sdk , where payfort php sdk plugin available. Just replace with your credentials in PayfortIntegration.php file.

**Comment by mbilal117** [comment]
Thanks @sanjaykumar2338  for prompt reply.
I am new to payfort and using python. I have created a form as mentioned in above post when i click submit it gives me 404 error.

<form id="payfort_payment" action="https://sbcheckout.payfort.com/FortAPI/paymentPage" method="POST">
    <input type="hidden" id="merchant_identifier" name="merchant_identifier" value="test">
    <input type="hidden" id="access_code" name="access_code" value="test">
    <input id="return_url" name="return_url" type="hidden" value="{% url 'test_url' %}">
    <input type="hidden" id="merchant_reference" name="merchant_reference" value="112">
    <input type="hidden" id="language" name="language" value="en">
    <input type="hidden" id="service_command" name="service_command" value="TOKENIZATION">
    <input type="hidden" id="signature" name="signature" value="{{ signature }}">
    <input type="hidden" id="card_number" name="card_number" value="4005550000000001">
    <input type="hidden" id="card_holder_name" name="card_holder_name" value="Mr Smith">
    <input type="hidden" id="card_security_code" name="card_security_code" value="123">
    <input type="hidden" id="expiry_date" name="expiry_date" value="2105">
    <input type="submit" value="pay"/>
</form>

**Comment by ramisalem** [comment]
@mohannadsaleh The email that you recommended is not found   integration@payfot.com

**Comment by ahmed-almawardy** [comment]
hey  guys ,

i have the same issue "Invalid extra parameters" i use Merchant page ,
however it was working before well, now it doesn't ,
i have emailed the payfort integration team to help but really till now , just they took my account name , and didn't help me ...... !!!!!
it is urgent matter i have a live project !!!!!!

**Comment by Dania310** [comment]
@AhmedElmawary Thanks for raising your concern.

Please note that each Account will have different setup and configuration as per the proposal signed with the Sales Team.In order to activate any channel you want to integrate like Merchant Page please contact ( support@payfort.com ) , and for the Integration technical issues please contact ( integration@payfort.com ).
