### ISSUE TITLE
Total amount of products and Remember me Parameter

### ISSUE THREAD

**Issue by mujtabagaints** [payfort/payfort-php-sdk#14]
I need help about how to pass total amount of my cart to the gateway. Help will appreciated.

**Comment by reda1987** [comment]
cloud you updated us with solution

**Comment by PayFortIntegration** [comment]
Hi , 

Please send us the issue which you experienced with clarifications to the email address "integration@payfort.com" to help you properly and further.

Thanks
Esraa
