### ISSUE TITLE
Getting issue - Invalid signature.

### ISSUE THREAD

**Issue by sanjaykumar2338** [payfort/payfort-php-sdk#17]
Parameter Name | Parameter Value
-- | --
amount | 10000
response_code | 00008
merchant_identifier | cjXYnVPO
access_code | QSCsH5s50WseQ5BWx8OA
order_description | Apple
payment_option | NAPS
customer_ip | 112.196.24.36
language | en
eci | ECOMMERCE
command | AUTHORIZATION
response_message | Signature mismatch
merchant_reference | 7347364551
customer_email | test@payfort.com
currency | USD
status | 00
error_msg | Invalid signature.

**Comment by sanjaykumar2338** [comment]
Hi, 
above issue resolved.

But I have two payment option master and visa so but I passed in payment option.

When i have to pass MasterCard it redirects me to payfort and again asking for card details. 

Regards.

**Comment by mohannadsaleh** [comment]
Hello,

Thank you for contacting us , glad you were able to fix the "Signature mismatch" for more continues support during the integration please contact integration@payfort.com they will follow up and support/certify your integration .

Best Regards, 
Mohannad Saleh

**Comment by sreez** [comment]
> 
> 
> Hi,
> above issue resolved.
> 
> But I have two payment option master and visa so but I passed in payment option.
> 
> When i have to pass MasterCard it redirects me to payfort and again asking for card details.
> 
> Regards.

Hi, How did you fix this issue ? I got the same one. 

> Error message: Signature mismatch

**Comment by Elie-Saliba** [comment]
> Hi,
> above issue resolved.
> 
> But I have two payment option master and visa so but I passed in payment option.
> 
> When i have to pass MasterCard it redirects me to payfort and again asking for card details.
> 
> Regards.

hi how did you solve the signature missmatch issue?

**Comment by sreez** [comment]
> 
> 
> > Hi,
> > above issue resolved.
> > But I have two payment option master and visa so but I passed in payment option.
> > When i have to pass MasterCard it redirects me to payfort and again asking for card details.
> > Regards.
> 
> hi how did you solve the signature missmatch issue?

this issue occurs during the development with sandbox mode enabled. payfort tracks each transaction using the signature generated from the order id. so when you are using the same id again maybe after resetting the installtion, it will generate this error.  To fix it I have to set the autoincrement id of the table "sequence_order_1" to a higher value. I dont know if there is a more easier option.

**Comment by Dania310** [comment]
@Elie-Saliba Thanks for raising your concern.

In order to assist you through the signature calculations , please contact us on this email ( integration@payfort.com ).
