### ISSUE TITLE
How can we make payment through the saved token cards

### ISSUE THREAD

**Issue by ajlouni-dev** [payfort/payfort-php-sdk#30]
Hello! Is this sample php script support the part related to the tokenization? How can we make a payment via the token/cards that are saved in our system? Thanks!

**Comment by PayFortIntegration** [comment]
Hi abdallah,
Can you please email us on integration@payfort.com and share your concerns in order to assist you properly.

Thanks.

**Comment by ajlouni-dev** [comment]
I'm contacting you through the email (drnutrition.com company), but it seems that you don't give support (as php script) for this part of the intergartion(the utilization of the saved card/token in the next transactions). Right?

**Comment by PayFortIntegration** [comment]
Hi Abdallah, 
Thank u for contacting us.
Yes this is correct we dont support the tokenization service in our PHP SDK code.
And as per our support team reply , you need to implement it from your end. 
Dont hesitate to contact us for any further assistance.
