### ISSUE TITLE
is this for real?

### ISSUE THREAD

**Issue by moealmaw** [payfort/payfort-php-sdk#7]
is this is the real official php implementation for the Payfort? and is it seriously an SDK? come on guys, PHP is much better than this :/

**Comment by mohannadsaleh** [comment]
Hello,

Thank for sharing your feedback ,  please be informed that  this sdk is created and maintained by PayFort team which we always keep adding and enhancing its core to support our merchants needs ,

Please feel to share with us your notes in details on the sdk or let's us know your contact details we will be glad to hear from you your notes 

Thank you in advance  
Best Regarde
Mohannad Saleh

**Comment by moealmaw** [comment]
Hello Mohannad,

I will take a look at your documentation and see what can be done to make this better.

**Comment by moealmaw** [comment]
Hello @mohannadsaleh 
I am trying to make an account on PayFort but it seems I must have a running website and I need to provide information about my business in order to get an account. I will need a demo account at least if I have to contribute anything for this sdk.
I am being contacted by Dalia El Gammal if you can do anything about it from your side.

**Comment by moealmaw** [comment]
@mohannadsaleh ..... ???

**Comment by mohannadsaleh** [comment]
Hello,

We have a process by our onboarding team which should be followed before giving access to the merchants , 

Please provide the team with the required details and they will create an account for you .

Best Regards
